[package]
name = "atom"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "bench"
harness = false
